src/components/draggable-popover/useDraggablePopoverStyles.ts
src/components/video-player/useVideoContainerStyles.ts

Fixes: https://github.com/Collaborne/backlog/issues/1027

Fit video player into all disponible width with an aspect ration of 16/9

---

src/hooks/use-delayed-state.ts

Fixes https://github.com/Collaborne/backlog/issues/1192

Memoize useDelayState hook's callbacks

---

.storybook/decorators/with-core-player.tsx
.storybook/stories/0-VideoPlayer.stories.tsx
.storybook/stories/10-VideoHighlights.stories.tsx
.storybook/stories/11-KaraokeMode.stories.tsx
.storybook/stories/12-AudioPlayer.stories.tsx
src/components/core-player/CorePlayer.tsx

Add by default 16/9 to `<CorePlayer />`

Add 16:9 aspect ratio as a default prop for the player

---

src/components/controls/Controls.tsx
src/components/draggable-popover/useDraggablePopoverHook.ts
src/components/media-container/useMediaContainerHook.ts

Fixes: [#1254 ](https://github.com/Collaborne/backlog/issues/1254)

Fix  showControls and showPipControls bug

---

.storybook/stories/0-MediaPlayer.stories.tsx
src/components/media-container/usePipHook.ts

Fixes: [#1253](https://github.com/Collaborne/backlog/issues/1253)

Add timeout for `onWheel` event that would toggle pip mode

---

.storybook/components/karaoke/utils.ts
.storybook/stories/11-KaraokeMode.stories.tsx
src/components/core-player/CorePlayer.tsx
src/context/MediaProvider.tsx
src/store/__tests__/media-store.spec.tsx
src/store/media-store.ts
src/types/emitters.ts
src/types/media-state-external-initializers.ts
src/types/media-state.ts
src/utils/__test__/array.spec.ts
src/utils/array.ts
src/utils/index.ts
src/utils/number.ts
src/utils/testing-render.tsx

- Add a time alarm event, that emit events for an array of seconds
Graphically, it would look like that:

Add `timeAlarm` event

---

src/components/bottom-control-buttons/components/FullscreenButton.tsx
src/components/bottom-control-buttons/components/FwdButton.tsx
src/components/bottom-control-buttons/components/PictureInPictureButton.tsx
src/components/bottom-control-buttons/components/PlayPauseReplay.tsx
src/components/bottom-control-buttons/components/PlaybackRateButton.tsx
src/components/bottom-control-buttons/components/RwdButton.tsx
src/components/bottom-control-buttons/components/VolumeButton.tsx
src/components/bottom-control-buttons/components/VolumeSlider.tsx
src/components/controls/Controls.tsx
src/components/draggable-popover/DraggablePopover.tsx
src/components/draggable-popover/useDraggablePopoverHook.ts
src/components/draggable-popover/usePipMouseActivity.ts
src/components/media-container/MediaContainer.tsx
src/components/media-container/useMediaContainerHook.ts
src/components/media-container/useMediaContainerStyles.ts
src/components/media-container/useMouseActivityHook.ts
src/components/media-container/useReactPlayerHook.ts
src/components/media-player/MediaPlayer.tsx
src/components/pip-controls/PipControls.tsx
src/components/pip-controls/usePipControlsHook.ts
src/context/MediaProvider.tsx
src/hooks/index.ts
src/hooks/use-on-hovered-element.ts
src/hooks/useOnHoveredControlElement.ts
src/types/media-state-external-initializers.ts

- Fixes: https://github.com/Collaborne/backlog/issues/1236
- some small refactor (related to multi usage of the useMediaStore)

Improve mouse events when hovering player and pip player

---

.github/workflows/build-doc.yml

This PR adds workflow for TypeDoc documentation update.
Fixes: https://github.com/Collaborne/backlog/issues/1124

Add build-doc workflow

---

.github/workflows/typedoc-update.yml
README.md
docs/interfaces/components_media_player_MediaPlayer.MediaPlayerProps.md
docs/interfaces/types_emitters.EmitterListeners.md
docs/interfaces/types_media_state.Highlight.md
docs/interfaces/types_media_state.MediaState.md
docs/interfaces/types_media_state.Segment.md
docs/interfaces/types_media_state_external_initializers.MediaStateExternalInitializers.md
docs/interfaces/types_media_state_setters.MediaStateSetters.md
docs/interfaces/types_react_player.ReactPlayerProps.md
docs/modules.md
docs/modules/components_media_player_MediaPlayer.md
docs/modules/types.md
docs/modules/types_emitters.md
docs/modules/types_media_state.md
docs/modules/types_media_state_external_initializers.md
docs/modules/types_media_state_setters.md
docs/modules/types_react_player.md
docs/modules/types_required_and_optional_pick.md
docs/modules/types_typings.md

This PR updates `TypeDoc` publish workflow from `main` branch to `PRs`.
Relates with: https://github.com/Collaborne/backlog/issues/1124

Typedoc flow trigger updated

---

README.md
docs/interfaces/components_media_player_MediaPlayer.MediaPlayerProps.md
docs/interfaces/types_emitters.EmitterListeners.md
docs/interfaces/types_media_state.Highlight.md
docs/interfaces/types_media_state.MediaState.md
docs/interfaces/types_media_state.Segment.md
docs/interfaces/types_media_state_external_initializers.MediaStateExternalInitializers.md
docs/interfaces/types_media_state_setters.MediaStateSetters.md
docs/interfaces/types_react_player.ReactPlayerProps.md
docs/modules.md
docs/modules/components_media_player_MediaPlayer.md
docs/modules/types.md
docs/modules/types_emitters.md
docs/modules/types_media_state.md
docs/modules/types_media_state_external_initializers.md
docs/modules/types_media_state_setters.md
docs/modules/types_react_player.md
docs/modules/types_required_and_optional_pick.md
docs/modules/types_typings.md

- update Readme.md avoiding "video" word usage and add some recipes 
- As a part of: https://github.com/Collaborne/backlog/issues/1108

Improve documentation in Readme.md

---

README.md
src/components/bottom-control-buttons/__tests__/usePlayBackRateButtonHook.spec.tsx
src/components/bottom-control-buttons/components/PlaybackRateButton.tsx
src/components/bottom-control-buttons/hooks/usePlaybackRateButtonHook.ts

Fixes: https://github.com/Collaborne/backlog/issues/1279
Before:
[Screencast from 26.10.2022 09:20:26.webm](https://user-images.githubusercontent.com/50721739/197949801-90b9dd39-7133-4a65-b751-81900eab8661.webm)
Now:
[Screencast from 26.10.2022 09:19:38.webm](https://user-images.githubusercontent.com/50721739/197949837-f6c40260-d5c9-43cf-aef0-a708bf0ca1af.webm)

Fix the playbackRate alghoritm (length vs currentIndex)

---

.storybook/stories/12-AudioPlayer.stories.tsx
.storybook/stories/13-CustomizedAudioPlayer.stories.tsx
package-lock.json
package.json
src/components/controls/useControlsStyles.ts
src/components/media-poster/MediaPoster.tsx
src/utils/index.ts

- update styles and relating to it used packages.
Issues related here:  https://github.com/garronej/tss-react/issues/25, https://github.com/mui/material-ui/issues/28045
- improve `< MediaPoster />` 
- add a custom story for audio player using the `<CorePlayer/>`

Improve experience for audio files

---

package-lock.json
package.json
src/components/big-centered-button/BigCenteredButton.tsx
src/components/bottom-control-buttons/BottomControlButtons.tsx
src/components/bottom-control-buttons/components/PlaybackRateButton.tsx
src/components/controls/Controls.tsx
src/components/core-player/CorePlayer.tsx
src/components/draggable-popover/DraggablePopover.tsx
src/components/media-container/MediaContainer.tsx
src/components/media-poster/MediaPoster.tsx

clsx processes merging of classnames differently from cx which is used in our other projects. This makes it diffcult to override default classnames

Replace clsx with mui cx

---

.storybook/stories/08-IconButtonsAndIcons.stories.tsx
src/components/bottom-control-buttons/BottomControlButtons.tsx
src/components/bottom-control-buttons/useBottomControlButtonsStyles.ts
src/components/bottom-controls/useBottomControlsStyles.ts
src/components/centered-bottom-playback/useCenteredBottomPlaybackStyles.ts
src/components/controls/Controls.tsx
src/components/controls/useControlsStyles.ts
src/components/draggable-popover/useDraggablePopoverStyles.ts
src/components/media-player/MediaPlayer.tsx
src/components/pip-controls/usePipControlsStyles.tsx
src/components/progress-bar/components/ProgressBarStyled.ts
src/components/progress-bar/useProgressBarStyles.ts
src/theme.ts
src/types/mui.d.ts

Fixes: https://github.com/Collaborne/backlog/issues/1256
- add backdropFilter to components that uses background.default and store it as a theme variable
- add primaryVeryDark constant, and apply it to `ProgressBar`'s track color
- fix PlaybackRate button height into PIP mode
- add `color=inherit` and `color=primary` to storybook
- remove background from Controls styling and apply it to BottomControls (that is used as for audio and video files)

Theme Refining

---

src/components/animated-icon-wrapper/AnimatedIconWrapper.tsx
src/components/bottom-control-buttons/components/TimeDisplay.tsx
src/components/bottom-control-buttons/components/VolumeSlider.tsx
src/components/bottom-controls/BottomControls.tsx
src/components/centered-bottom-playback/CenteredBottomPlayback.tsx
src/components/play-pause-animation/PauseAnimation.tsx
src/components/play-pause-animation/PlayAnimation.tsx
src/components/progress-bar/ProgressBar.tsx

Extend UI Components with a `className` (in case they have missed it) for external styling

Add `className` prop for UI elements

---

src/components/bottom-control-buttons/components/VolumeButton.tsx

Fixes: https://github.com/Collaborne/backlog/issues/1318

Fix `onToggleMute` for the `<VolumeButton />`

---

.storybook/components/custom-pip-controls/CustomPipControls.tsx
.storybook/stories/1-CustomPIPControls.stories.tsx
src/components/core-player/CorePlayer.tsx
src/components/draggable-popover/DraggablePopover.tsx
src/components/draggable-popover/useDraggablePopoverStyles.ts
src/context/PIPControlsProvider.tsx
src/context/pipControls.ts
src/hooks/use-pip-controls-context.ts

- Fixes: https://github.com/Collaborne/backlog/issues/1336
- Calibrate `<ProgressBar />`

Add `PIPControls` to allow UI configs on PipPlayer

---

.storybook/stories/0-MediaPlayer.stories.tsx
.storybook/stories/7-DraggablePopover.stories.tsx
src/components/core-player/CorePlayer.tsx
src/components/draggable-popover/DraggablePopover.tsx
src/components/draggable-popover/useDraggablePopoverHook.ts
src/components/draggable-popover/useDraggablePopoverStyles.ts
src/components/media-container/MediaContainer.tsx
src/components/pip-controls/PipControls.tsx
src/components/pip-controls/usePipControlsStyles.tsx

- add possibility to change  `x, y` appearance of the pip player
- add possibility to pass `className` for `ReactPlayer` wrapper (in case if we want to hide visibility)
- move `<ProgressBar />` into `< PipControls />` - it's just standard behavior of component `<PipControls />`, not of the pip mode

Refine `PIP Player` and add props for customing initialization of `x, y`

---

README.md
package-lock.json
package.json
tasks/refresh-readme.ts

As a part of the https://github.com/Collaborne/backlog/issues/1326
- Rename `video-player` repo to `media-player`

Rename package to @collaborne/media-player

---

.storybook/stories/11-KaraokeMode.stories.tsx
src/store/media-store.ts

Fixes: https://github.com/Collaborne/backlog/issues/1345

Reset alarms on `setCurrentTIme`

---

.gitignore
README.md
package-lock.json
package.json
tasks/create-coverage-badge.ts

Fixes: https://github.com/Collaborne/backlog/issues/1326
- Create coverage files and badge and add them to the gh-pages deploy

Build coverage files and add them to the deploy folder for gh-pages

---

.storybook/stories/0-MediaPlayer.stories.tsx
src/components/core-player/CorePlayer.tsx
src/components/draggable-popover/DraggablePopover.tsx
src/components/draggable-popover/useDraggablePopoverHook.ts
src/components/draggable-popover/useDraggablePopoverStyles.ts
src/components/media-container/MediaContainer.tsx
src/utils/media-utils.ts

- remove scroll bar sizing
- get the width and height from portal wrapper
- add possibilities for easy controling of the dragging box of the pip player
- update storybook

Resizing and dragging PIP player into a "box"

---

package.json

Fixes https://github.com/Collaborne/backlog/issues/1502

Don't include source files into build artifact

---

src/components/core-player/CorePlayer.tsx
src/components/draggable-popover/DraggablePopover.tsx
src/components/draggable-popover/useDraggablePopoverStyles.ts
src/components/media-container/MediaContainer.tsx
src/components/media-container/usePipHook.ts
src/components/media-container/useReactPlayerProps.ts
src/components/media-player/MediaPlayer.tsx
src/components/player/Player.tsx
src/components/player/usePlayerHook.ts

Fixes: https://github.com/Collaborne/backlog/issues/1507
- remove setTimeouts for the `PIP`
- collect `reactplayerprops` outside of the `Player` component (on every remount is shouldnt not be recreated)
- memo `MediaPlayer` and `CorePlayer` (avoid rerender caused by non-related props changed)

Remove timeouts for the PIP mode

---

package-lock.json
src/context/MediaProvider.tsx

- Fix and test (link repos) in:
- `c-share-app` (here we have linking issues, so after deploying new fixed version of m-player check it )

Fix `zustand` migration

---

package-lock.json
package.json

- update react-player
- add it as a peer dependency

Update react player and add is as a peer dependency

---

src/components/progress-bar/ProgressBar.tsx
src/store/media-store.ts

- Fixes: https://github.com/Collaborne/backlog/issues/2199
- Use duration in `<ProgressBar />`

Pause ReactPlayer when user initialized duration reaches end
