Collaborne/media-player

.storybook/stories/12-AudioPlayer.stories.tsx, src/types/typings.d.ts, src/utils/video.utils.ts
This is first part of the : https://github.com/Collaborne/backlog/issues/1030 :
— just adding new story into the storybook that plays an audio file path 
When we will have all details on how it should UI/UX be, another PR will be created, for closing the current ticket (including karaoke mode on this audio).
=> Introduce audio file path into video-player

.storybook/components/random-highlight/RandomHighlight.tsx, .storybook/stories/10-VideoHighlights.stories.tsx, .storybook/utils/highlights.ts, src/components/progress-bar/ProgressBar.tsx, src/components/progress-bar/__test__/create-rails-list.spec.ts, src/components/progress-bar/components/Rail.tsx, src/components/progress-bar/components/RailStyled.ts, src/components/progress-bar/components/RailsList.tsx, src/components/progress-bar/components/Track.tsx, src/components/progress-bar/components/TrackSegment.tsx, src/components/progress-bar/utils/create-rails-list.ts, src/components/video-player/VideoPlayer.tsx, src/context/video.tsx, src/store/actions.ts, src/store/getters.ts, src/store/reducer.ts, src/types/actions.ts, src/types/getters.ts, src/types/video-state.ts, src/utils/__tests__/highlights.spec.ts, src/utils/colors.ts
Decoupling `highlights` from video-state:
- there is no necessity in storing highlights into video-state.
- correcting `Highlight`  interface `color`  from `string` to `string[]`
=> Decouple highlights from video-state

package-lock.json, package.json
Newer version of the react-intl library break the texts when running in local development mode. Considering that there are no meaningful development on the library: we'll fix it at the latest working version.
@see https://collaborne.slack.com/archives/C10KC7128/p1662794453876839
=> Fix latest working react-intl version

.storybook/stories/11-KaraokeMode.stories.tsx, src/components/video-player/VideoPlayer.tsx, src/context/VideoProvider.tsx, src/store/actions.ts, src/store/reducer.ts, src/types/emitters.ts, src/types/video-state.ts
=> Correct typings for `EmitterEvents` in `VideoState` and add children for `VideoPlayer`

src/hooks/__test__/use-delayed-state.spec.tsx, src/hooks/index.ts, src/hooks/use-delayed-state.ts, src/utils/index.ts, src/utils/sleep.ts
_Cannot update a component (`CenteredReplayButton`) while rendering a different component (`VideoProvider`). To locate the bad setState() call inside `VideoProvider`, follow the stack trace as described in ..._
What does it means:
1.  `CenteredReplayButton` is subscribed to API `EventEmitters`:
```ts
// `end` event is emitted when media playing reached the end of the duration
useEventListener(
'end',
() => {
if (!hasStarted) {
return;
}
setIsFinished(true);
},
api as unknown as HTMLElement,
);
```
2. `CenteredReplayButton` updates it own state and wants to rerender
3. `VideoProvider`(Parent) is not yet updated (when calling `play` - `pause`... and other `VideoApi` state setters, we _first emit_ events, _after_ that we _update_ the `VideoState`). This causes that error to happen. …
=> Add delayed state setter for fixing errors that are related to subscribing `EventEmitters`

.storybook/stories/11-KaraokeMode.stories.tsx, src/hooks/__test__/use-video-listener.spec.ts, src/hooks/index.ts, src/hooks/use-video-listener.ts
As a part of the  [add a event listener for VideoApi](https://github.com/Collaborne/backlog/issues/1132)
Adds a hook that will simplify the usage of the video listeners.
- What IDE thinks about it:
or live session coding:
https://user-images.githubusercontent.com/50721739/192029192-68f8f8ea-596f-4b3b-8ae2-b06711e2d6d2.mp4
=> Add video event listener hook

.storybook/stories/10-VideoHighlights.stories.tsx, .storybook/stories/11-KaraokeMode.stories.tsx, src/hooks/__test__/use-player-context.spec.tsx, src/hooks/index.ts, src/hooks/use-player-context.ts
-  `usePlayerContext` - as a part of the [ticket](https://github.com/Collaborne/backlog/issues/1132)
As a usage for:
```ts
import {
VideoPlayer,
useCorePlayer,
useDelayedState,
useVideoListener,
} from '@collaborne/video-player';
const Component = () => {
const { setVideoContext, videoContextApi } = useCorePlayer();
const [play, setIsPlaying] = useDelayedState();
useVideoListener('play', () => setIsPlaying(true), videoContextApi);
return <VideoPlayer onContext={onContext} videoUrl="some-url" />;
};
```
=> Create `usePlayerContext` hook to avoid boilerplate

.storybook/stories/10-VideoHighlights.stories.tsx, src/store/actions.ts, src/types/emitters.ts
There can be the case where we would need the video duration (progress bars or outside usage of the `EventEmitters`).
`onDuration` prop from ReactPlayer runs `api.setDuration` (setter for the video duration) when video is ready to play, but do not run any emitters.
Update video listeners
=> Add `durationchange` event for VideoApi

src/components/video-container/useVideoContainerHook.ts, src/context/VideoProvider.tsx, src/context/video.tsx, src/store/actions.ts, src/store/getters.ts, src/store/reducer.ts, src/types/actions.ts, src/types/getters.ts, src/types/video-state.ts
To make VideoContext lighter, decided to remove unused state or behaviours
Unused states:
- `loop` - should loop video
- `lastActivityRef`- after last refactoring, its logic is used in `useContainerHook`
=> Remove unused state in VideoState

src/hooks/__test__/use-player-context.spec.tsx, src/hooks/use-player-context.ts
As context is stored in a ref, we need to force a rerender when `VideoContext` is ready, otherwise it will export an undefined ref
=> Rerender when context is defined

src/components/bottom-control-buttons/hooks/usePlaybackRateStyles.ts
Before, the Playback button would only have the same size because it was always placed next to a larger button. Now, the Playback button has the same size - even if it stays alone.
Required for https://github.com/Collaborne/backlog/issues/1190
=> Enforce consistent size for Playback button

.storybook/stories/0-MediaPlayer.stories.tsx, src/components/media-container/usePipHook.ts
At every wheel event now we call `onWheel` function.
The purpose of this ticket is to throttle `onWheel`.
Fixes: https://github.com/Collaborne/backlog/issues/1237
=> Throttle `wheel` event to prevent unnecesarry callbacks

docs/interfaces/components_media_player_MediaPlayer.MediaPlayerProps.md, docs/interfaces/types_emitters.EmitterListeners.md, docs/interfaces/types_media_state.Highlight.md, docs/interfaces/types_media_state.MediaState.md, docs/interfaces/types_media_state.Segment.md, docs/interfaces/types_media_state_external_initializers.MediaStateExternalInitializers.md, docs/interfaces/types_media_state_setters.MediaStateSetters.md, docs/interfaces/types_react_player.ReactPlayerProps.md, docs/modules/types_emitters.md, docs/modules/types_required_and_optional_pick.md, src/components/draggable-popover/useDraggablePopoverStyles.ts
- remove default paper "grayish" background that wraps media container
- make it inline-flex, to allow its children to "flex"
Fixes: https://github.com/Collaborne/backlog/issues/1224
=> "Center" videos and remove "greyish" background on aspect ratios different than `16/9`

package-lock.json, package.json, src/components/controls/Controls.tsx, src/components/media-container/useMediaContainerStyles.ts, src/components/media-poster/MediaPoster.tsx, src/components/media-poster/useMediaPosterStyles.ts, src/index.ts
- Export `utils` 
- remove unused `@use-it/event-listener`
- add `className` prop for `<Controls />`
- mofidy `MediaPoster` to get children as props (using plain `@mui/styled` - falls into error if we add `ReactNode`)
=> Export `utils` and remove unused `@use-it/event-listener` and fix MediaPoster

src/components/core-player/CorePlayer.tsx, src/components/core-player/useCorePlayerHook.ts, src/components/media-container/MediaContainer.tsx, src/context/MediaProvider.tsx, src/hooks/use-media-type.ts, src/types/media-state-external-initializers.ts, src/types/media-type.ts
Add unknown instead of unsupported and leave the flow to continue, even if the file extension is unknown
=> Do not return null for unknown media types

.storybook/stories/0-MediaPlayer.stories.tsx, .storybook/stories/12-AudioPlayer.stories.tsx, .storybook/stories/13-CustomizedAudioPlayer.stories.tsx, src/components/core-player/CorePlayer.tsx, src/components/core-player/components/ExternalStateUpdater.tsx, src/components/core-player/useCorePlayerHook.ts, src/store/__tests__/media-store.spec.tsx, src/store/media-store.ts, src/types/media-state-setters.ts
The issue:
- When we form `MediaProvider` with [initialization store values](https://github.com/Collaborne/video-player/blob/669af656ac563efd65dbbe11b812a90a6c05c38a/src/context/MediaProvider.tsx#L59-L79), if these values are changed(as example: media type, alarms...), these updates do not trigger updates in the `MediaStore` (they just initialize it )
- add initializtion value for media type, that will be primary source of truth
Solution:
- Create a empty React Component(should be children of `MediaProvider`), that will catch updates from outside the `MediaProvider`, and update the store
Fixes: https://github.com/Collaborne/backlog/issues/1328
=> Allow `MediaStore` to be updated from `CorePlayer` props and internal state

package-lock.json, package.json, src/components/bottom-control-buttons/__tests__/BottomControlButtons.spec.tsx, src/components/bottom-control-buttons/__tests__/usePlayBackRateButtonHook.spec.tsx, src/components/bottom-control-buttons/components/FullscreenButton.tsx, src/components/bottom-control-buttons/components/FwdButton.tsx, src/components/bottom-control-buttons/components/PictureInPictureButton.tsx, src/components/bottom-control-buttons/components/PlayPauseReplay.tsx, src/components/bottom-control-buttons/components/PlaybackRateButton.tsx, src/components/bottom-control-buttons/components/RwdButton.tsx, src/components/bottom-control-buttons/components/VolumeButton.tsx, src/components/bottom-control-buttons/components/VolumeSlider.tsx, src/components/core-player/components/ExternalStateUpdater.tsx, src/components/draggable-popover/DraggablePopover.tsx, src/components/draggable-popover/usePipMouseActivity.ts, src/components/media-container/MediaContainer.tsx, src/components/media-container/useIsPlayerReadyHook.ts, src/components/media-container/useMouseActivityHook.ts, src/components/media-container/usePipHook.ts, src/components/pip-controls/PipControls.tsx, src/components/pip-controls/usePipControlsHook.ts, src/components/player/Player.tsx, src/components/player/useReactPlayerHook.ts, src/components/progress-bar/ProgressBar.tsx, src/hooks/use-on-hovered-element.ts, src/hooks/use-play-pause-replay.ts
- apply swallow for multiple store slices: https://github.com/pmndrs/zustand#selecting-multiple-state-slices
- store `currentTime` in a ref(get it from `timeupdate` event) and use in places where it do not need a refresh UI(ex: forward/rewind buttons)
- `ReactPlayer` use in a memo component and distribute it to MediaContainer(avoid MediaContainer to collect for ReactPlayer props, that can trigger its children) 
- `ProgressBar` - use value as: [0.01,0.02] instead of [0.000001, 0.000011]  - this will save rerebders
- Using multiple selectors without "shallow" - you will lose "atomic" part of the store(something similar to redux's mapStateToProps) and your selector will update as often as MediaStore does(~on every 100 ms)
zustand [docs](https://github.com/pmndrs/zustand#selecting-multiple-sta …
=> Avoid rerenders caused by unappropriate store selectors and `currentTime`

package.json, src/components/animated-icon-wrapper/AnimatedIconWrapper.tsx, src/components/big-centered-button/BigCenteredButton.tsx, src/components/bottom-control-buttons/BottomControlButtons.tsx, src/components/bottom-control-buttons/__tests__/BottomControlButtons.spec.tsx, src/components/bottom-control-buttons/components/FullscreenButton.tsx, src/components/bottom-control-buttons/components/PictureInPictureButton.tsx, src/components/bottom-control-buttons/components/PlayPauseReplay.tsx, src/components/centered-bottom-playback/CenteredBottomPlayback.tsx, src/components/centered-bottom-playback/__tests__/CeneredBottomPlayback.spec.tsx, src/components/centered-play-button/CenteredPlayButton.tsx, src/components/controls/Controls.tsx, src/components/draggable-popover/DraggablePopover.tsx, src/components/media-container/MediaContainer.tsx, src/components/media-player/__test__/MediaPlayer.spec.tsx, src/components/play-pause-animation/PauseAnimation.tsx, src/components/play-pause-animation/PlayAnimation.tsx, src/components/player/Player.tsx, src/components/progress-bar/ProgressBar.tsx, src/utils/constants.ts
As a part of Integration tests: https://github.com/Collaborne/backlog/issues/1326
=> MediaPlayer: Integration tests for first time media playing

.storybook/stories/0-MediaPlayer.stories.tsx, src/components/bottom-control-buttons/components/PictureInPictureButton.tsx, src/components/core-player/CorePlayer.tsx, src/components/draggable-popover/DraggablePopover.tsx, src/components/draggable-popover/useDraggablePopoverHook.ts, src/components/media-container/MediaContainer.tsx, src/components/media-container/usePipHook.ts, src/utils/html-elements.ts, src/utils/index.ts
- ### Keep always PIP player on screen when resizing window
Screen Recording: 
https://user-images.githubusercontent.com/50721739/203644857-d5dfede8-f115-4c6c-a499-22381884196b.mp4
-  ### Bug with resizing on PIP mode
1. Play a video
2. Enter PIP mode
3. Resize window
Screen Recording: 
https://user-images.githubusercontent.com/50721739/203644962-dee94b8e-e96b-403b-ba38-7dbd407ee583.mp4
- ### Activate PIP from scroll, return into view and press PIP button is failed
1. Play a video in a container that can be scrolled
2. scroll down to be PIP mode appeared
3. scroll up to main player(pip dissapears)
4. press on PIP button
Screen Recording:
https://user-images.githubusercontent.com/50721739/203708696-97435eea-a1f0-49a5-a3d5-ad7760b6e742.mp4
=> Fix PIP resizing bug styling and keep PIP mode always on screen

src/components/controls/Controls.tsx, src/components/media-player/__test__/MediaPlayer.spec.tsx
- fix bug with dissapering controls in MediaPlayer(audio mode)
- update tests
=> Always display controls on audio player

src/components/draggable-popover/DraggablePopover.tsx, src/components/draggable-popover/useDraggablePopoverStyles.ts, src/components/media-container/usePipHook.ts
- Trigger PIP mode if player is not in the viewport (no more dependencies on wheel event)
- fix time losing between switching modes
**NOTE: Everytime when PIP mode goes on/off we remount the `<Player/>` component[children of [DraggablePopover](https://github.com/Collaborne/media-player/blob/e19f66cb5b1b286e9c4e340682c6ee7a65ba16c7/src/components/draggable-popover/DraggablePopover.tsx#L85)] (because of portal), and this causes losing time of the player (prop [onProgress](https://github.com/Collaborne/media-player/blob/e19f66cb5b1b286e9c4e340682c6ee7a65ba16c7/src/components/player/useReactPlayerHook.ts#L78) is created with 0 playedSeconds on every mount), and this is the reason why we need to use timeouts in [usePipHook](https://github.com/Collaborne/media-player/blob/e19f66cb5b1b286e9c4e340 …
=> Remove wheel event from the PIP "callers"

.storybook/decorators/with-media-wrapper.tsx, .storybook/stories/13-CustomizedAudioPlayer.stories.tsx
- Add same picture for stories, to avoid chromatic detecting UI changes, when no changes was made to the UI
Ex: chromatic always see random images as a change:
=> Add unsplash image insetad of random picsum photo

src/components/media-player/MediaPlayer.tsx
As `MediaPlayer` is de facto player in many instances, and when pip is disabled, we shall hide it from controls
=> Remove PIP button for media player when pip state is disabled

.storybook/stories/14-InitialState.stories.tsx, .storybook/utils/doc.ts, src/components/core-player/types.ts, src/components/media-container/useReactPlayerProps.ts, src/components/player/Player.tsx, src/components/player/usePlayerHook.ts, src/context/MediaProvider.tsx, src/store/media-store.ts, src/types/media-state-external-initializers.ts, src/utils/constants.ts
As a part of :https://github.com/Collaborne/backlog/issues/1999
- Add `autoPlay` initial prop
- clean up non-working/unused/untested functionality of the `CorePlayerInitialState`
`CorePlayerInitialState`— not used in `c-app-ui`, and the only way we want to use it is to start with autoPlay,
=> Add `autoPlay` initial prop

.storybook/stories/14-InitialState.stories.tsx, src/components/core-player/types.ts, src/components/media-container/useReactPlayerProps.ts, src/components/player/usePlayerHook.ts, src/context/MediaProvider.tsx, src/store/media-store.ts, src/types/media-state-external-initializers.ts, src/utils/constants.ts
- extend `CorePlayerInitialState` with durationSeconds field
- create a storybook to validate new created prop
- add `initialState` to the `MediaStore` and update `duration` from `initialState`(events emitting should not be broken)
=> Keep control of media's total duration via `initialState` prop

src/components/progress-bar/components/ProgressBarStyled.ts
When adding a transition(here we have set a 0.3s) =>  creates a delay between current progress + 0.3s, which causes inconsistency between UI (MuiThumb vs MuiTrack)
=> Remove transition for Slider(used in Progress Bars)

.vscode/settings.json
Fixes: https://github.com/Collaborne/backlog/issues/2048
- issue on **[stackoverflow](https://stackoverflow.com/questions/74642723/how-do-i-force-vs-code-to-always-use-my-workspaces-version-of-typescript-for-al)**
=> Use common workspace typescript's settings for project
